default:
  image: node:15

stages:
  - test_and_build
  - build_and_publish

test:
  stage: test_and_build

  before_script:
    - yarn install

  script:
    - yarn test:unit
    - yarn build

release:
  stage: build_and_publish

  before_script:
    - yarn install

  script:
    - yarn build
    - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' > .npmrc
    - npm publish

  only:
    - master
