stages:
  - test
  - build
  - publish

test:
  stage: test
  image: node:15

  before_script:
    - yarn install

  script:
    - yarn test:unit

build:
  stage: build
  image: node:15

  before_script:
    - yarn install

  script:
    - yarn build

publish:
  stage: publish
  image: node:15

  before_script:
    - yarn install

  script:
    - yarn build
    - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' > .npmrc
    - npm publish

  only:
    - master
